### ISSUE TITLE
Bot tries to autoban himself on first-joining a group

### ISSUE THREAD

**Issue by federicotorrielli** [federicotorrielli/antibot-telegram-bot#2]
From the logs:

`2020-10-06T15:52:17.851273+00:00 app[worker.1]: Exception in thread Thread-54:
2020-10-06T15:52:17.851315+00:00 app[worker.1]: Traceback (most recent call last):
2020-10-06T15:52:17.851321+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2020-10-06T15:52:17.851809+00:00 app[worker.1]:     self.run()
2020-10-06T15:52:17.851811+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/threading.py", line 870, in run
2020-10-06T15:52:17.852189+00:00 app[worker.1]:     self._target(*self._args, **self._kwargs)
2020-10-06T15:52:17.852193+00:00 app[worker.1]:   File "antiflood.py", line 48, in on_message
2020-10-06T15:52:17.852293+00:00 app[worker.1]:     bot.kickChatMember(msg['chat']['id'], msg['new_chat_members'][0]['id'])
2020-10-06T15:52:17.852295+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/amanobot/__init__.py", line 814, in kickChatMember
2020-10-06T15:52:17.852596+00:00 app[worker.1]:     return self._api_request('kickChatMember', _rectify(p))
2020-10-06T15:52:17.852599+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/amanobot/__init__.py", line 505, in _api_request
2020-10-06T15:52:17.853013+00:00 app[worker.1]:     return api.request((self._token, method, params, files),
2020-10-06T15:52:17.853016+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/amanobot/api.py", line 170, in request
2020-10-06T15:52:17.853298+00:00 app[worker.1]:     return _parse(r, raise_errors)
2020-10-06T15:52:17.853317+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/amanobot/api.py", line 164, in _parse
2020-10-06T15:52:17.853459+00:00 app[worker.1]:     raise exception.TelegramError(description, error_code, data)
2020-10-06T15:52:17.853555+00:00 app[worker.1]: amanobot.exception.TelegramError: ("Bad Request: can't restrict self", 400, {'ok': False, 'error_code': 400, 'description': "Bad Request: can't restrict self"})`

I suggest we dig into this ASAP, but it's causing no harm to the bot itself.

**Comment by federicotorrielli** [comment]
fixed in commit 87079feaa4c70eeceb7ba5deae4753f9800042b8
